### PR TITLE
[FIX] Unicode #3 and multiline msgids #4

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
Sorry for cramming both fixes into one PR but I have too little time at the moment to learn GitHub properly ;-)

**Comment by ankitpopli1891** [comment]
@antiflu No worries mate, and Thanks for the contribution. Will update on pypi ASAP.

**Comment by thomaspaulb** [comment]
Before you do that quickly review how I integrated the paid Google API.

On a sidenote, maybe not to be discussed here, but during the next week I will make autotranslate packages for django-cms and django-parler as well - I want them to depend on this one, what do you think

**Comment by ankitpopli1891** [comment]
I have already reviewed the Google API, I do have some changes in mind, but they are trivial, and can be done later.

Sounds cool. Just let me know if I can be of any assistance.

**Comment by thomaspaulb** [comment]
Mm the only thing I am so far unsure about is how to deal effectively with
garbling of %s, %(s) and HTML constructs... if you have any ideas, I was
thinking also to see how Rosetta deals with that. Only thing that has come
to mind so far is to replace them by numbers and later replace them back.

**Comment by ankitpopli1891** [comment]
I haven't given any thought to this till now, and neither I have checked how Rosetta handles that. I'll try to figure this out when I have some time. 

Meanwhile, contributions will be accepted ;)

**Pull request merged**
