### PR TITLE
added plural forms support

### PR DESCRIPTION
**Pull request by generalov**
I've added support for plural forms.

```
msgid "City"
msgid_plural "Cities"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
msgstr[3] ""
```

This PR is about the filling the `msgstr[0]` with `msgid` translation and rest of `msgstr[N]` with `msgid_plural` translation.

I've added the `six` to requirements.txt too.

### CODE REVIEW

**Comment by ankitpopli1891** [comment]
@generalov Just FYI, I'll be able to test and release the version by the end of next week.

Thanks a lot for the contribution.

Cheers!!

**Comment by ankitpopli1891** [comment]
@generalov Can you please sync your repo to get the latest Travis-CI conf.

Thanks

**Comment by generalov** [comment]
Done. 

I've checked the Django Python compability docs and I've updated the tox.ini according that (see the list of environments `tox -l`). There were unsupported and unrecommended combinations.

https://docs.djangoproject.com/en/1.9/releases/1.5/#python-compatibility
https://docs.djangoproject.com/en/1.9/releases/1.6/#python-compatibility
https://docs.djangoproject.com/en/1.9/releases/1.7/#python-compatibility
https://docs.djangoproject.com/en/1.9/releases/1.8/#python-compatibility
https://docs.djangoproject.com/en/1.9/releases/1.9/#python-compatibility

I've just removed the py3.2 from the environment list because the `goslate` raises SyntaxError in Python-3.2. 

You may to reduce the number of dj-py combinations in the .travis.yml too.

**Comment by ankitpopli1891** [comment]
@generalov Thanks a ton for all the hard work. 

I've also updated the Travis YAML as you suggested.

Thanks

**Pull request merged**
