### PR TITLE
Improved the %(placeholder)s keeping strategy

### PR DESCRIPTION
**Pull request by generalov**
This PR is about format placeholders in the `msgid` strings. Positional: `%s`, `%d`,  and named: `%(name)s`. The Google Translate service translates them, but they shouldn't be changed.

I've removed the `s` and `d` suffixes from placeholders before translation to reduce the noise (and restored them late). Additionally this PR keeps the %(placeholder) names untranslated. 

Some tests and multi-environment tox.ini are added too.

// I'm sorry for my silly English

### CODE REVIEW

**Comment by ankitpopli1891** [comment]
Hey @generalov,

Awesome work. I've been thinking of putting in some tests for quite some time. Thanks a lot for the head start.

Just a quick query, using the `__placeholder__` is quite an awesome idea, but is it documented anywhere that google translate will ignore these kind of strings? Infact I'm looking forward to implement other translation backends as well, so that could be a problem there I suppose.

Shouldn't we use numbers instead? Or we should do something else. What's your say?

**Comment by generalov** [comment]
At the first, I've tried just strip format specifier from placeholders reducing them to `%(name)`, but in some languages Google changes the symbols position. For example:

```
msgid "Delete selected %(name)s!"
msgstr "Eliminare% selezionato (name)!"
```

(note the `%` symbol position). I don't know how to recover from this.

Then I've changed escaping to form of  the `__placeholder__`. I don't have any apriory knowledge about Google formats. It seems Google keeps such words untranslated.

The current implementation still has anomaly.  I've got at result:

```
msgid "Delete selected %(name)s!"
msgstr "Eliminare %(name)sselezionata!"
```

(here one space is lost) 

> Shouldn't we use numbers instead

Yes, may be you are right. I've missed such case.

I don't know how this strategy will work with another translation engine. Most likely it is Google specific.

**Comment by ankitpopli1891** [comment]
Escaping to `__placeholder__` form is absolutely a brilliant move. It does provide a lot of coverage. 

But I came across this case where I translated a simple named variable `__awesome__` and the result varied according to the language being translated. For instance:

In **Afrikaans**, translation remained same i.e `__awesome__`, while in **Albanian** it turned out to be `__mbresëlënës__`. 

And regarding the numbers thing, I'm yet not sure whether the translation remains same. I write a small script to find this out and update you ASAP. 

Meanwhile, I'll merge this PR, since it improves the coverage a lot and release the package on PyPi. Sounds good?

**Comment by generalov** [comment]
Thanks, I would be very grateful for that. :)

**Pull request merged**
